---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: service-b-mtls
    namespace: service-b
spec:
    mtls:
      mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
    name: service-b-policy
    namespace: service-b
spec:
    selector:
      matchLabels:
        app: service-b
    rules:
      - from:
          - source:
              principals: ["cluster.local/ns/service-a/sa/service-a"]
        to:
          - operation:
              methods: ["GET", "POST"]
              paths: ["/api/*"]
      - from:
          - source:
              principals: ["cluster.local/ns/orchestrator/sa/orchestrator"]
        to:
          - operation:
              methods: ["GET"]
              paths: ["/metrics", "/healthz"]