---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: service-a-mtls
    namespace: service-a
spec:
    mtls:
      mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
    name: service-a-policy
    namespace: service-a
spec:
    selector:
      matchLabels:
        app: service-a
    rules:
      - from:
          - source:
              principals: ["cluster.local/ns/service-b/sa/service-b"]
        to:
          - operation:
              methods: ["GET", "POST"]
              paths: ["/api/*"]
      - from:
          - source:
              principals: ["cluster.local/ns/orchestrator/sa/orchestrator"]
        to:
          - operation:
              methods: ["GET"]
              paths: ["/metrics", "/healthz"]