apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    phase: poc
    compliance-mode: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        phase: poc
        compliance-mode: sandbox
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        mesh.status: "pending"
    spec:
      containers:
        - name: service-a
          image: python:3.11-slim
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args: ["pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8080"]
          workingDir: /app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: SERVICE_MODE
              value: "sandbox"
            - name: COMPLIANCE_PHASE
              value: "poc"
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          hostPath:
            path: /workspaces/example-service/services/service-a
            type: Directory