apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    phase: poc
    compliance-mode: sandbox
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-a