[project]
name = "example-service"
version = "0.1.0"
description = "Example service golden template"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
