openapi: 3.0.0
info:
  title: Service A API
  version: "1.0.0"
  description: POC implementation for Phase 4 compliance flow
paths:
  /healthz:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service health status
  /api/v1/data:
    get:
      summary: Sample data endpoint
      responses:
        '200':
          description: Returns sample data with POC metadata