apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - name: http
    port: 8001
    targetPort: http
  - name: metrics
    port: 8000
    targetPort: metrics