groups:
- name: service-c-alerts
  rules:
  - alert: ServiceCHighLatency
    expr: histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=~"service-c.*"}[5m])) by (le)) > 1000
    for: 5m
    labels:
      severity: warning
      service: service-c
    annotations:
      summary: "Service-C High Latency"
      description: "Service-C P95 latency is above 1000ms for 5 minutes"

  - alert: ServiceCHighErrorRate
    expr: sum(rate(istio_requests_total{destination_service=~"service-c.*",response_code=~"5.*"}[5m])) / sum(rate(istio_requests_total{destination_service=~"service-c.*"}[5m])) * 100 > 5
    for: 2m
    labels:
      severity: critical
      service: service-c
    annotations:
      summary: "Service-C High Error Rate"
      description: "Service-C error rate is above 5% for 2 minutes"

  - alert: ServiceCLowThroughput
    expr: sum(rate(istio_requests_total{destination_service=~"service-c.*"}[5m])) < 1
    for: 5m
    labels:
      severity: warning
      service: service-c
    annotations:
      summary: "Service-C Low Throughput"
      description: "Service-C is receiving less than 1 request per second for 5 minutes"

  - alert: ServiceCCircuitBreakerTripped
    expr: istio_circuit_breaker_triggered{destination_service=~"service-c.*"} > 0
    for: 1m
    labels:
      severity: critical
      service: service-c
    annotations:
      summary: "Service-C Circuit Breaker Tripped"
      description: "Circuit breaker has been tripped for Service-C"