apiVersion: v2
name: service-b
description: Service B for Sprint 2 Mesh Validation
version: 0.1.0
appVersion: "1.0.0"

---
# Default values for service-b
replicaCount: 2

image:
  repository: httpd
  tag: alpine
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "service-b"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

deployment:
  name: service-b-deployment

podAnnotations:
  sidecar.istio.io/inject: "true"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

serviceAccount:
  create: true
  name: "service-b"