---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: parallel-promotion
spec:
    hosts:
    - "*.service-mesh.local"
    gateways:
    - mesh-gateway
    http:
    - match:
      - uri:
          prefix: "/service-a"
      route:
      - destination:
          host: service-a
          subset: current
        weight: 90
      - destination:
          host: service-a
          subset: candidate
        weight: 10
    - match:
      - uri:
          prefix: "/service-b"
      route:
      - destination:
          host: service-b
          subset: current
        weight: 90
      - destination:
          host: service-b
          subset: candidate
        weight: 10
    - match:
      - uri:
          prefix: "/service-c"
      route:
      - destination:
          host: service-c
          subset: current
        weight: 100 # No candidate yet