---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-c
    labels:
      app: service-c
      phase: poc
      compliance-mode: sandbox
spec:
    replicas: 1
    selector:
      matchLabels:
        app: service-c
    template:
      metadata:
        labels:
          app: service-c
          phase: poc
          compliance-mode: sandbox
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"
          mesh.status: "enforced"
      spec:
        containers:
          - name: service-c
            image: python:3.11-slim
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c"]
            args: ["pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8080"]
            workingDir: /app
            ports:
              - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 20
            env:
              - name: SERVICE_MODE
                value: "sandbox"
              - name: COMPLIANCE_PHASE
                value: "sprint2"
              - name: MESH_ENABLED
                value: "true"