---
---
# Source: service-c/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
    name: service-c-release-name
    labels:
      app.kubernetes.io/name: service-c
      app.kubernetes.io/instance: release-name
spec:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
    selector:
      app.kubernetes.io/name: service-c
      app.kubernetes.io/instance: release-name
---
# Source: service-c/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-c-release-name
    labels:
      app.kubernetes.io/name: service-c
      app.kubernetes.io/instance: release-name
spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: service-c
        app.kubernetes.io/instance: release-name
    template:
      metadata:
        labels:
          app.kubernetes.io/name: service-c
          app.kubernetes.io/instance: release-name
        annotations:
          sidecar.istio.io/inject: "true"
      spec:
        containers:
          - name: service-c
            image: "nginx:stable"
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
