---
persistence:
    enabled: true
    size: 1Gi

resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

sidecar:
    dashboards:
      enabled: true
      defaultFolderName: General
      provider:
        foldersFromFilesStructure: true
      searchNamespace: ALL