apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Secret
metadata:
  name: example-service-secrets
  namespace: staging
type: Opaque
data:
  STAGING_TOKEN: ${STAGING_TOKEN}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - name: example-service
        image: ghcr.io/fintech-blueprint/example-service:latest  # Will be replaced by CI
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: example-service-secrets
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: staging
spec:
  selector:
    app: example-service
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP