name: Audit and Compliance

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_run:
    workflows: ["CI Pipeline", "Auto-Generate Code from Specs", "Validate Specifications"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  issues: write

jobs:
  audit:
    name: Security and Compliance Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for audit trail

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r patch_requirements.txt

    - name: Generate audit trail
      run: |
        python scripts/audit_compliance.py --generate-trail
        
    - name: Validate specification coverage
      run: |
        python scripts/validate_spec_coverage.py --threshold 90
      run: python scripts/validate_spec_coverage.py

    - name: Resource estimation
      run: python scripts/resource_estimator.py

    - name: Upload audit reports
      uses: actions/upload-artifact@v3
      with:
        name: audit-reports
        path: |
          reports/
          generated/
        retention-days: 30

    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Audit Check Failure',
            body: 'Daily audit checks have failed. Please review the workflow logs and artifacts.'
          })