name: Auto-Generate Code from Specs

on:
  workflow_run:
    workflows: ["Validate Specifications"]
    types:
      - completed

jobs:
  generate-code:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install generator deps
        run: |
          pip install jinja2

      - name: Download spec coverage report
        uses: actions/download-artifact@v3
        with:
          name: spec-coverage-report
          path: reports


