name: CI Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install flake8
      - run: flake8 src tests

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest --maxfail=1 --disable-warnings -q

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: python
      - uses: github/codeql-action/analyze@v2

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test, sast]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t example-service:${{ github.sha }} .

  sbom-sign:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v3
      - name: Generate SBOM
        run: |
          pip install cyclonedx-bom
          cyclonedx-py -o sbom.xml
      - name: Sign image (cosign)
        run: |
          echo "placeholder for cosign signing"
          # Placeholder: after docker build, update staging-env manifest (to be implemented)
