name: CI Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install flake8
      - run: flake8 src tests

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run tests
        run: |
          PYTHONPATH=$PWD pytest --maxfail=1 --disable-warnings -q

  sast:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow this job to fail since GHAS isn't enabled
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # Remove sast from needs since it's optional
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t example-service:${{ github.sha }} .

  sbom-sign:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate SBOM
        run: |
          pip install cyclonedx-bom
          # Generate SBOM using correct command syntax (no -r flag)
          cyclonedx-py requirements requirements.txt -o sbom.xml

      - name: Sign image (cosign)
        run: |
          echo "placeholder for cosign signing"
          # Placeholder: after docker build, update staging-env manifest (to be implemented)
