name: Build and Deploy

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github-actions
        aws-region: us-east-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      env:
        REGISTRY: ${{ secrets.ECR_REGISTRY }}
        REPOSITORY: example-service
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    name: Deploy with Vault Auth
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: OIDC Auth to Vault
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.example.com
        role: github-actions
        method: jwt
        jwtGithubAudience: "https://github.com/Fintech-Blueprint"
        secrets: |
          secret/data/deployment/creds access_key | AWS_ACCESS_KEY;
          secret/data/deployment/creds secret_key | AWS_SECRET_KEY

    - name: Deploy to Production
      env:
        AWS_ACCESS_KEY: ${{ env.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ env.AWS_SECRET_KEY }}
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        # Deploy using AWS credentials from Vault
        echo "Deploying version $IMAGE_TAG to production"
        # Add deployment commands here