name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
        check-type: ['code-style']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Log Environment Info
        run: |
          echo "Python Version: ${{ matrix.python-version }}"
          echo "OS: ${{ matrix.os }}"
          echo "Check Type: ${{ matrix.check-type }}"
          python --version
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint actionlint-py flake8 black isort
          
      - name: Run YAML Lint
        run: |
          echo "Running YAML linting..."
          yamllint --strict .
          
      - name: Run Action Lint
        run: |
          echo "Running GitHub Actions linting..."
          curl -L -o /usr/local/bin/actionlint https://github.com/rhysd/actionlint/releases/download/v1.7.0/actionlint_linux_amd64
          chmod +x /usr/local/bin/actionlint
          actionlint
          
      - name: Run Python Linters
        run: |
          echo "Running Python code style checks..."
          black --check .
          isort --check-only .
          flake8 .
      
      - name: Upload Lint Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            reports/lint/
            reports/flake8/
          retention-days: 7