---
# IMPORTANT:
# - Always start file with '---'
# - Use explicit lists for branches/tags, never inline truthy
# - Split run: commands >80 chars into block scalars
# - Max line length: 80
# - Use consistent variable names from global spec
name: Lint Code
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        lint-type: ['python', 'yaml', 'docker']
    steps:
      - uses: actions/checkout@v4
      - name: Log job metadata
        run: |
          echo "Start time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "Python version: ${{ matrix.python-version }}"
          echo "Lint type: ${{ matrix.lint-type }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r patch_requirements.txt
          pip install pylint black isort yamllint hadolint-py
      - name: Run linting
        id: lint
        run: |
          case "${{ matrix.lint-type }}" in
            "python")
              echo "Running Python linting..."
              pylint src/ || exit 1
              black --check src/ || exit 1
              isort --check-only src/ || exit 1
              ;;
            "yaml")
              echo "Running YAML linting..."
              yamllint . || exit 1
              ;;
            "docker")
              echo "Running Dockerfile linting..."
              hadolint Dockerfile || exit 1
              ;;
          esac
      - name: Log completion
        if: always()
        run: |
          echo "Lint completed for ${{ matrix.lint-type }}"
          echo "End time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-${{ matrix.lint-type }}
          path: |
            pylint.txt
            black.txt
            isort.txt
            yamllint.txt
            hadolint.txt
          retention-days: 7
