---
# Lint Code Workflow (CTO Guardrails Compliant)
name: Lint Code
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black isort yamllint hadolint-py
      - name: Create reports folder
        run: mkdir -p reports
      - name: Run pylint
        run: pylint src/ > reports/pylint.txt || true
      - name: Run black
        run: black --check src/ > reports/black.txt || true
      - name: Run isort
        run: isort --check-only src/ > reports/isort.txt || true
      - name: Run yamllint
        run: yamllint . > reports/yamllint.txt || true
      - name: Run hadolint
        run: |
          if [ -f Dockerfile ]; then
            hadolint Dockerfile > reports/hadolint.txt || true
          else
            echo "No Dockerfile found" > reports/hadolint.txt
          fi
      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: reports/
