name: Service-B CI/CD Pipeline

on:
  push:
    paths:
      - 'services/service-b/**'
      - '.github/workflows/service-b.yml'
  pull_request:
    paths:
      - 'services/service-b/**'
      - '.github/workflows/service-b.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        working-directory: services/service-b
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-httpx pylint safety
      
      - name: Run linting
        working-directory: services/service-b
        run: |
          pylint *.py
      
      - name: Security scan
        working-directory: services/service-b
        run: |
          safety check
      
      - name: Run tests
        working-directory: services/service-b
        run: |
          pytest

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check service-a compliance
        run: |
          STATUS=$(curl -s http://service-a.service-a-poc.svc.cluster.local:8080/healthz | jq -r .mode)
          if [ "$STATUS" != "compliant" ]; then
            echo "service-a is not in compliant state (current: $STATUS)"
            exit 1
          fi

  build-evidence:
    needs: [validate, dependency-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up evidence collection
        run: |
          mkdir -p audit/services/service-b/evidence/$(date +%Y%m%d)/{sast,tests,metrics}
      
      - name: Collect SAST results
        run: |
          # Placeholder for actual SAST tool
          echo "{\"scan_time\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"findings\": []}" > \
            audit/services/service-b/evidence/$(date +%Y%m%d)/sast/results.json
      
      - name: Upload evidence
        uses: actions/upload-artifact@v3
        with:
          name: compliance-evidence
          path: audit/services/service-b/evidence

  promote:
    if: github.ref == 'refs/heads/main'
    needs: build-evidence
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download evidence
        uses: actions/download-artifact@v3
        with:
          name: compliance-evidence
          path: audit/services/service-b/evidence
      
      - name: Prepare promotion request
        run: |
          # This will use service-b's promotion preparation script (to be implemented)
          echo "Preparing promotion request..."
      
      - name: Submit promotion request
        run: |
          # This will be implemented when promotion service is ready
          echo "Submitting promotion request..."