name: Test ORG_GH_TOKEN

on:
  workflow_dispatch:

jobs:
  test-token:
      - name: Authenticate to Vault and fetch ORG_GH_TOKEN
        id: vault-login
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          role: github-actions-role
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            secret/data/ci/org_gh_token ORG_GH_TOKEN

      - name: Try safe repo dispatch
        env:
          ORG_GH_TOKEN: ${{ env.ORG_GH_TOKEN }}
        run: |
          HTTP_STATUS=$(curl -s -o /tmp/dispatch_response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $ORG_GH_TOKEN" \
            https://api.github.com/repos/Fintech-Blueprint/example-service/dispatches \
            -d '{"event_type":"test-dispatch","client_payload":{"test":"ok"}}')
          echo "Dispatch response code: $HTTP_STATUS"
          if [ "$HTTP_STATUS" != "204" ]; then
            echo "Dispatch failed; cat /tmp/dispatch_response.json:"
            cat /tmp/dispatch_response.json || true
            exit 1
          fi
            exit 1
          fi
