name: Test ORG_GH_TOKEN

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check ORG_GH_TOKEN presence
        run: |
          echo "ORG_GH_TOKEN is set? ->"
          if [ -z "$ORG_GH_TOKEN" ]; then
            echo "❌ ORG_GH_TOKEN is empty"
            exit 1
          else
            echo "✅ ORG_GH_TOKEN is present"
          fi

      - name: Try safe repo dispatch
        run: |
          HTTP_STATUS=$(curl -s -o /tmp/dispatch_response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $ORG_GH_TOKEN" \
            https://api.github.com/repos/Fintech-Blueprint/example-service/dispatches \
            -d '{"event_type":"test-dispatch","client_payload":{"test":"ok"}}')
          echo "Dispatch response code: $HTTP_STATUS"
          if [ "$HTTP_STATUS" != "204" ]; then
            echo "Dispatch failed; cat /tmp/dispatch_response.json:"
            cat /tmp/dispatch_response.json || true
            exit 1
          fi
