name: Test ORG_GH_TOKEN

on:
  workflow_dispatch:
  push:
    branches:
      - 'fix/workflow-yaml'

jobs:
  test-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        id: debug
        run: |
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/Fintech-Blueprint" | jq .
          echo "Token contents:"
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/Fintech-Blueprint" | jq -r .value | cut -d. -f2 | base64 -d | jq .

      - name: Vault OIDC Login
        id: vault
        uses: hashicorp/vault-action@v2
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: ci-github-actions
          path: jwt
          jwtGithubAudience: "vault"
          secrets: |
            secret/data/ci/org_gh_token org_gh_token

      - name: Check ORG_GH_TOKEN presence
        run: |
          echo "ORG_GH_TOKEN is set? ->"
          if [ -z "$ORG_GH_TOKEN" ]; then
            echo "❌ ORG_GH_TOKEN is empty"
            exit 1
          else
            echo "✅ ORG_GH_TOKEN is present"
          fi

      - name: Try safe repo dispatch
        env:
          ORG_GH_TOKEN: ${{ env.ORG_GH_TOKEN }}
        run: |
          HTTP_STATUS=$(curl -s -o /tmp/dispatch_response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $ORG_GH_TOKEN" \
            https://api.github.com/repos/Fintech-Blueprint/example-service/dispatches \
            -d '{"event_type":"test-dispatch","client_payload":{"test":"ok"}}')
          echo "Dispatch response code: $HTTP_STATUS"
          if [ "$HTTP_STATUS" != "204" ]; then
            echo "Dispatch failed; cat /tmp/dispatch_response.json:"
            cat /tmp/dispatch_response.json || true
            exit 1
          fi
