name: Test Vault OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Vault (OIDC)
        id: vault-login
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          role: github-actions-role
          secrets: |
            secret/data/ci/org_gh_token ORG_GH_TOKEN

      - name: curl test dispatch (safe)
        env:
          ORG_GH_TOKEN: ${{ env.ORG_GH_TOKEN }}
        run: |
          echo "HTTP status from repo dispatch:"
          HTTP=$(curl -s -o /tmp/dispatch.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $ORG_GH_TOKEN" \
            https://api.github.com/repos/Fintech-Blueprint/example-service/dispatches \
            -d '{"event_type":"test-dispatch","client_payload":{"test":"ok"}}')
          echo "HTTP: $HTTP"
          if [ "$HTTP" != "204" ] && [ "$HTTP" != "201" ]; then
            echo "Dispatch failed, content:"
            cat /tmp/dispatch.json || true
            exit 1
          fi
          echo "Dispatch OK"
