---
# IMPORTANT:
# - Always start file with '---'
# - Use explicit lists for branches/tags, never inline truthy
# - Split run: commands >80 chars into block scalars
# - Max line length: 80
# - Use consistent variable names from global spec
name: Validate Token

on:
  workflow_call:
    inputs:
      token:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Token
        run: |
          echo "Validating token..."
          if [[ -z "${{ inputs.token }}" ]]; then
            echo "Token missing!" >&2
            exit 1
          fi
          # Add actual validation logic here
          echo "Token: ${{ inputs.token }}"
