name: Validate BDD Specifications

on:
  pull_request:
    paths:
      - '**/*.feature'
      - '.copilot-instructions.md'

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave
          
      - name: Create reports directory
        run: mkdir -p reports
        
      - name: Validate specifications
        run: python scripts/validate_specs.py --out reports/spec-coverage.json
        
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spec-coverage-report
          path: reports/spec-coverage.json